engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- test
- client/public
- client/test
- client/test/__mocks__
- e2e
- server/models
- server/seeders
